test-sugon.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
PR 테스트 완료했습니다. 검토 부탁 해요!
resolves #3
=> 🧪 feature: PR 테스트 resolve #[3]

test-psh.js
- [] 버그 수정
- [] 코드 리팩토링
PR 테스트 완료했어서 검토 부탁해요~~
resolves #7
=> PR 테스트 - psh

test-yong.js
- [v] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [v] 문서 수정
- [v] 파일 혹은 폴더명 수정
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
PR 테스트 완료했어서 검토 부탁해요~~
resolves #1
=> PR 테스트 완료했습니다~

src/pages/cleaning/cleaning.ts, src/pages/cleaning/index.html
레드불 게임플레이 에어리어 작업
resolves #44
=> Cleaning kyo

src/pages/health/index.html
- celebrate 이미지 경로 수정
- 성공 페이지 스타일 추가
- 실패 페이지 스타일 추가
resolves #40
=> 🎨 style: 결과 화면 스타일 추가

src/pages/cleaning/cleaning.ts, src/pages/cleaning/index.html, src/pages/cleaning/style.css
게임 종료후 점수에따라 성공,실패 페이지 구현
resolves #45
=> 결과 페이지 : 성공과 실패

src/pages/study/study-start.html, src/pages/study/study-start.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 퀴즈 게임 메인 화면 소스코드 수정
- 게임 시작 시 퀴즈문제 랜덤하게 출력 되도록 구현 완료
resolves #26
=> ✨ feat: 게임 시작할때마다 랜덤한 문제 출력

src/pages/study/study-start.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 게임 시작  할때마다 문제가 랜덤하게 출제되도록 구현
- OX 버튼을 누를 때마다 다음 문제로 넘어가도록 구현
- 마지막 5문제까지 넘어갔을 때 더이상 버튼 동작 안하도록 구현
resolves #28
=> ✨ feat:  문제 5개 출력, OX 버튼 누르면 다음 문제로 넘어가도록 구현 완료

src/pages/study/study-start.html, src/pages/study/study-start.ts
- [] 버그 수정
- [] 문서 수정
- 게임 화면에서 문제를 풀면 오른쪽 상단 상황판에 유저가 고른 답과 실제 문제의 답을 비교하여 맞췄는지 틀렸는지 O/X로 표시됨
- 상황판 디자인 변경
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #23
=> ✨ feat: 유저가 고른 답에 따른 정답 여부 판단하여 정/오답 처리 및 상황판에 출력 기능 구현

src/pages/study/study-start.html, src/pages/study/study-start.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- UI: 되돌아가기 버튼 기능 구현을 위해 id 속성 추가
- 기능: 되돌아가기 버튼 요소에 메인 화면 링크 추가 완료
resolves #24
=> ✨ feat: 되돌아가기 버튼 클릭 시 메인화면으로 돌아가는 기능 구현

src/pages/study/study-start.html, src/pages/study/study-start.ts, src/pages/study/style.css
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
1. UI 작업
- 엔딩 페이지 추가(전체 정답, 전체 오답)
2. 기능 작업
- 유저가 푼 답이 모두 정답인지 비교하여 맞으면 전체 정답 페이지로 이동하도록 구현
- 유저가 푼 답이 모두 오답인지 비교하여 맞으면 전체 오답 페이지로 이동하도록 구현
resolves #30
=> ✨ feat: 엔딩페이지 전체 정답, 전체 오답 처리 기능 구현

src/pages/study/study-start.html, src/pages/study/study-start.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 5문제중 일부만 맞췄을 때 넘어가는 UI 추가 완료
- 문제 결과를 체크하여 관련 페이지(일부 정답만 맞춘 페이지)로 이동하돌고 기능 구현
resolves #32
=> feat: 5문제중 일부만 맞췄을 때 해당 페이지 넘어가도록 기능 구현

src/pages/study/study-start.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 퀴즈 맞춘 정답 개수에 따라 exPoint 증가 기능 구현
resolves #33
=> ✨ feat:  로컬스토리지로 exPoint 저장 기능 구현

src/pages/health/health.ts
- 게임에서 획득한 경험치 메인 페이지로 전달 기능 구현
- 게임 성공 시 획득할 경험치 값
- 획득 경험치를 로컬 스토리지에 저장하도록
resolves #42
=> ✨ feat:  경험치 전달 기능 추가

src/pages/study/index.html, src/pages/study/study.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- HTML id 속성 변경
- 엔딩 페이지 별 버튼 이벤트 수정
resolves #60
=> ✨ feat: 각 엔딩 페이지별 게임 메인으로 되돌아갈 수 있도록 버튼 이벤트 수정

src/main.js, src/pages/cleaning/cleaning.js, src/pages/cleaning/cleaning.ts, src/pages/cleaning/index.html, src/pages/cleaning/style.css, src/pages/health/health.js, src/pages/health/health.ts, src/pages/health/index.html, src/pages/health/style.css, src/pages/main/index.html, src/pages/main/main.js, src/pages/main/main.ts, src/pages/main/style.css, src/pages/study/index.html, src/pages/study/study.js, src/pages/study/study.ts, src/pages/study/style.css, src/style.css, tsconfig.json, vite.config.js
- [] 새로운 기능 추가
- [] 문서 수정
- 전체페이지들 CSS 통일화 (css작업하면서 script도 함께 수정됐음 각자 페이지 변화 확인 필요)
- 전체 페이지들 스토리지 데이터값 연결 (경험치 수치/체력 수치/페이지 변화/단계 레벨 값 변화)
resolves #74
=> ♻️ refactor:  전반적인 CSS작업 및 코드리펙토링

index.html, src/main.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #62
=> feat: 대표 페이지 UI 및 기능 작업

src/assets/js/introduce.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
2차 배포
resolves #79
=> 🌐 deploy: 2차 배포

README.md
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #
=> 🧪 test:  main내용 병합

README.md
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 🧪 test:  배포 전 빌드 테스트

src/pages/cleaning/index.html, src/pages/health/health.js, src/pages/health/health.ts, src/pages/main/index.html, src/pages/main/main.js, src/pages/main/main.ts, src/style.css
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
[청소하기]
- (수정완료) redbull 이미지 안나옴
- (수정완료) 카운트 글자크기 너무큼
[메인]
- (수정완료) 버튼 글자 두 줄로 나옴
- (수정완료) 각 경험치 구간마다 바로바로 모습 변경 안됨
- (수정완료) play 화면 캔이 쌓여있다가 다른 작업후 돌아오면 캔이 사라져있음 
[운동하기]
- (수정완료) 성공했을 시 경험치 ( + 4 ) , 성공 사운드가 2번 들립니다.
[잠자기]
- (수정완료) 잠자기 페이지 들어왔을 때 일어나기 버튼 두번 누를 시 사운드가 멈추지 않습니다.
- (수정완료) 맥스 경험치 도달 후 잠자기 버튼을 누르면 , 엔딩 화면과 함께 코골이 사운드가 멈추지 않습니다.
resolves #89
=> 🐞 fix:  3차 배포관련 버그 및 이슈 수정
